# -*- coding: utf-8 -*-
"""task2_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BzShMrspfMGLjMZ1VJRGAw0ZGSjb3UcT

# Regression model

## Data import
"""

import numpy as np
import keras
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pandas as pd
from numpy.typing import ArrayLike
import tensorflow as tf
from module import time_to_float, time_to_float_old

# Load the small dataset to start training
x_75 = np.load("A1_data_75/images.npy")
y_75 = np.load("A1_data_75/labels.npy")
x_75 = x_75 / 255.0

# Split into training and test set and shuffle and since the datasets are ordered,
# it is recommended in the assignment spec to shuffle
x_75_train, x_75_test, y_75_train, y_75_test = train_test_split(x_75, y_75,
                        test_size = 0.10, random_state = 2029197, shuffle = True)

# Split again into training-validation sets
x_75_train, x_75_validation, y_75_train, y_75_validation = train_test_split(x_75_train, y_75_train,
                        test_size = 0.10, random_state = 202197, shuffle = True)

# Convert y sets into continuous numbers
y_75_train_old = time_to_float_old(y_75_train)
y_75_test_old = time_to_float_old(y_75_test)
y_75_validation_old = time_to_float_old(y_75_validation)
y_75_train = time_to_float(y_75_train)
y_75_test = time_to_float(y_75_test)
y_75_validation = time_to_float(y_75_validation)

# Add channel to train data
x_train_conv = x_75_train.reshape(x_75_train.shape[0], 75, 75, 1)
x_test_conv = x_75_test.reshape(x_75_test.shape[0], 75, 75, 1)
x_validation_conv = x_75_validation.reshape(x_75_validation.shape[0], 75, 75, 1)

# Load the small dataset to start training
x_150 = np.load("A1_data_150/images.npy")
y_150 = np.load("A1_data_150/labels.npy")
x_150 = x_150 / 255.0

# Split into training and test set and shuffle and since the datasets are ordered,
# it is recommended in the assignment spec to shuffle
x_150_train, x_150_test, y_150_train, y_150_test = train_test_split(x_150, y_150,
                        test_size = 0.10, random_state = 2029197, shuffle = True)

# Split again into training-validation sets
x_150_train, x_150_validation, y_150_train, y_150_validation = train_test_split(x_150_train, y_150_train,
                        test_size = 0.10, random_state = 202197, shuffle = True)

# Convert y sets into continuous numbers
y_150_train_old = time_to_float_old(y_150_train)
y_150_test_old = time_to_float_old(y_150_test)
y_150_validation_old = time_to_float_old(y_150_validation)
y_150_train = time_to_float(y_150_train)
y_150_test = time_to_float(y_150_test)
y_150_validation = time_to_float(y_150_validation)

# Add channel to train data
x_train_conv_150 = x_150_train.reshape(x_150_train.shape[0], 150, 150, 1)
x_test_conv_150 = x_150_test.reshape(x_150_test.shape[0], 150, 150, 1)
x_validation_conv_150 = x_150_validation.reshape(x_150_validation.shape[0], 150, 150, 1)

"""## Model 1"""

model = keras.models.Sequential(layers=[
    keras.layers.Conv2D(filters=150,
                        kernel_size=(2,2),
                        padding="same",
                        kernel_initializer="random_normal",
                        bias_initializer="zeros",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=300,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=75,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Flatten(),
    keras.layers.Dense(units=75,
                       activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")
])
model.compile(optimizer="sgd",
              loss="mse",
              metrics=[circular_mae_old])
history = model.fit(x_train_conv, y_75_train_old, epochs=30,
                    validation_data=(x_validation_conv, y_75_validation_old))

pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.title("Accuracy and loss in training and validation")
plt.xlabel("Epochs")
plt.ylabel("Accuracy/Loss")
plt.show()

results = model.evaluate(x_test_conv, y_75_test_old)
results

"""## Model 2"""

model = keras.models.Sequential(layers=[
    keras.layers.Conv2D(filters=150,
                        kernel_size=(2,2),
                        padding="same",
                        kernel_initializer="random_normal",
                        bias_initializer="zeros",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=150,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(2),
    keras.layers.Conv2D(filters=300,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=300,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(2),
    keras.layers.Conv2D(filters=75,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=75,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(2),
    keras.layers.Flatten(),
    keras.layers.Dense(units=150,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(units=75,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(units=75,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dense(1, activation="sigmoid")
])
early_stop = keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0002,
    patience=3,
    start_from_epoch=30
)
reduce_lr = keras.callbacks.ReduceLROnPlateau(monitor='val_circular_mae_old', factor=0.8,
                              patience=5, min_lr=0.00001)
optimiser = keras.optimizers.Adam(learning_rate = 0.0001)
model.compile(optimizer=optimiser,
              loss="huber",
              metrics=[circular_mae_old])
history = model.fit(x_train_conv, y_75_train_old, epochs=30,
                    validation_data=(x_validation_conv, y_75_validation_old),
                    callbacks = [early_stop, reduce_lr])

pd.DataFrame(history.history).plot(figsize=(8, 5), label = ["Train Circular MAE", "Train Loss", "Validation Circular MAE", "Validation Loss"])
plt.grid(True)
plt.title("Accuracy and loss in training and validation")
plt.xlabel("Epochs")
plt.ylabel("Accuracy/Loss")
plt.show()

results = model.evaluate(x_test_conv, y_75_test_old)
results

model = keras.models.Sequential(layers=[
    keras.layers.Conv2D(filters=150,
                        kernel_size=(2,2),
                        padding="same",
                        kernel_initializer="random_normal",
                        bias_initializer="zeros",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=150,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(2),
    keras.layers.Conv2D(filters=300,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=300,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(2),
    keras.layers.Conv2D(filters=75,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=75,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(2),
    keras.layers.Flatten(),
    keras.layers.Dense(units=150,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(units=75,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(units=75,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dense(1, activation="sigmoid")
])
early_stop = keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0002,
    patience=3,
    start_from_epoch=30
)
reduce_lr = keras.callbacks.ReduceLROnPlateau(monitor='val_circular_mae_old', factor=0.8,
                              patience=5, min_lr=0.00001)
optimiser = keras.optimizers.Adam(learning_rate = 0.0001)
model.compile(optimizer=optimiser,
              loss="huber",
              metrics=[circular_mae_old])
history = model.fit(x_train_conv_150, y_150_train_old, epochs=30,
                    validation_data=(x_validation_conv_150, y_150_validation_old),
                    callbacks = [early_stop, reduce_lr])

pd.DataFrame(history.history).plot(figsize=(8, 5), label = ["Train Circular MAE", "Train Loss", "Validation Circular MAE", "Validation Loss"])
plt.grid(True)
plt.title("Accuracy and loss in training and validation")
plt.xlabel("Epochs")
plt.ylabel("Accuracy/Loss")
plt.show()

results = model.evaluate(x_test_conv_150, y_150_test_old)
results

"""## Model 3"""

model = keras.models.Sequential(layers=[
    keras.layers.Conv2D(filters=75,
                        kernel_size=(3,3),
                        padding="same",
                        kernel_initializer="random_normal",
                        bias_initializer="zeros",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=75,
                        kernel_size=(3,3),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(pool_size=(2,2)),
    keras.layers.Conv2D(filters=150,
                        kernel_size=(3,3),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=150,
                        kernel_size=(3,3),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(pool_size=(2,2)),
    keras.layers.Conv2D(filters=35,
                        kernel_size=(3,3),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=35,
                        kernel_size=(3,3),
                        padding="same",
                        activation="relu"),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(pool_size=(2,2)),
    keras.layers.Flatten(),
    keras.layers.Dense(units=150,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(units=75,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(units=35,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dense(1, activation="linear")
])
early_stop = keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0002,
    patience=3,
    start_from_epoch=10
)
optimiser = keras.optimizers.Adam(learning_rate = 0.0001)
model.compile(optimizer=optimiser,
              loss="huber",
              metrics=[circular_mae])
history = model.fit(x_train_conv, y_75_train, epochs=30,
                    validation_data=(x_validation_conv, y_75_validation),
                    callbacks = [early_stop])

pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.title("Accuracy and loss in training and validation")
plt.xlabel("Epochs")
plt.ylabel("Accuracy/Loss")
plt.show()

results = model.evaluate(x_test_conv, y_75_test)
results

"""## Model 4"""

model = keras.models.Sequential(layers=[
    keras.layers.Conv2D(filters=75,
                        kernel_size=(2,2),
                        padding="same",
                        kernel_initializer="random_normal",
                        bias_initializer="zeros",
                        activation="relu",
                         kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=75,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(pool_size=(2,2)),
    keras.layers.Conv2D(filters=150,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=150,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(pool_size=(2,2)),
    keras.layers.Conv2D(filters=35,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=35,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.Flatten(),
    keras.layers.Dense(units=150,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(units=75,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(units=35,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dense(1, activation="linear")
])
early_stop = keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0002,
    patience=5,
    start_from_epoch=20
)
reduce_lr = keras.callbacks.ReduceLROnPlateau(monitor='val_circular_mae', factor=0.8,
                              patience=5, min_lr=0.00001)
optimiser = keras.optimizers.Adam(learning_rate = 0.0001)
model.compile(optimizer=optimiser,
              loss="huber",
              metrics=[circular_mae])
history = model.fit(x_train_conv, y_75_train, epochs=30,
                    validation_data=(x_validation_conv, y_75_validation),
                    callbacks = [early_stop, reduce_lr])

pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.title("Accuracy and loss in training and validation")
plt.xlabel("Epochs")
plt.ylabel("Accuracy/Loss")
plt.show()

results = model.evaluate(x_test_conv, y_75_test)
results

model = keras.models.Sequential(layers=[
    keras.layers.Conv2D(filters=75,
                        kernel_size=(2,2),
                        padding="same",
                        kernel_initializer="random_normal",
                        bias_initializer="zeros",
                        activation="relu",
                         kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=75,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(pool_size=(2,2)),
    keras.layers.Conv2D(filters=150,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=150,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(pool_size=(2,2)),
    keras.layers.Conv2D(filters=35,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.Conv2D(filters=35,
                        kernel_size=(2,2),
                        padding="same",
                        activation="relu",
                        kernel_regularizer=keras.regularizers.L2(0.0001)),
    keras.layers.BatchNormalization(),
    keras.layers.Flatten(),
    keras.layers.Dense(units=150,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(units=75,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(units=35,
                       activation="relu"),
    keras.layers.LayerNormalization(),
    keras.layers.Dense(1, activation="linear")
])
early_stop = keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0002,
    patience=5,
    start_from_epoch=20
)
reduce_lr = keras.callbacks.ReduceLROnPlateau(monitor='val_circular_mae', factor=0.8,
                              patience=5, min_lr=0.00001)
optimiser = keras.optimizers.Adam(learning_rate = 0.0001)
model.compile(optimizer=optimiser,
              loss="huber",
              metrics=[circular_mae])
history = model.fit(x_train_conv_150, y_150_train, epochs=30,
                    validation_data=(x_validation_conv_150, y_150_validation),
                    callbacks = [early_stop, reduce_lr])

pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.title("Accuracy and loss in training and validation")
plt.xlabel("Epochs")
plt.ylabel("Accuracy/Loss")
plt.show()

results = model.evaluate(x_test_conv_150, y_150_test)
results