# -*- coding: utf-8 -*-
"""task2_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESlf6SZryROjsyNxEAVTk6Fc1CjhUOVd

# Task 2: Develop a Tell-the-Time Network
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from statistics import mean
from module import time_to_float


# Load the small dataset to start training
x_75 = np.load("A1_data_75/images.npy")
y_75 = np.load("A1_data_75/labels.npy")

# Normalise inputs, as in task 1
x_75 = x_75.astype('float32') / 255.0

# Split into training and test set and shuffle and since the datasets are ordered, it is recommended in the assignment spec to shuffle
x_75_train, x_75_test, y_75_train, y_75_test = train_test_split(x_75, y_75, test_size = 0.10, random_state = 2029197, shuffle = True)

# Split again into training-validation sets
x_75_train, x_75_validation, y_75_train, y_75_validation = train_test_split(x_75_train, y_75_train, test_size = 0.10, random_state = 202197)

tf.random.set_seed(202197)

"""## Subtask: Classification Model

### Data preparation
"""

# Given grayscale images it has to be added to the information i.e. shape from (n,75,75) to (n,75,75,1)
x_75_train_cat = np.expand_dims(x_75_train, axis=-1)
x_75_validation_cat = np.expand_dims(x_75_validation, axis=-1)
x_75_test_cat = np.expand_dims(x_75_test, axis=-1)

# Function to bin time labels into x minute intervals
def split_into_bins(label, tot_minutes=30):
    """
    Groups time into inverals of total minutes (tot_minutes)
    30 minutes -> 24 groups
    15 minutes -> 48 groups
    10 minutes -> 72 groups
    5 minutes -> 144 groups
    1 minute -> 720 groups
    """
    arr = np.empty(label.shape[0], dtype=object)
    for i in range(label.shape[0]):
        hours = label[i][0]
        minutes = label[i][1]
        minute_bins=  minutes//tot_minutes
        new_label = f'{hours}:{minute_bins*tot_minutes:02d}'
        arr[i] = new_label
    return arr

arrays = [y_75_train, y_75_validation, y_75_test]

# Make categorical tests for 30 (24 classes), 15 (48 classes) and 10 (72 classes) minutes intervals
y_75_categorical_24 = [split_into_bins(arr,30) for arr in arrays]
y_75_categorical_48 = [split_into_bins(arr,15) for arr in arrays]
y_75_categorical_72 = [split_into_bins(arr,10) for arr in arrays]

# Turn the string-based categories into factors in order to let our model know that this is a categorical variable
factor24 = LabelEncoder()
factor24.fit(np.concatenate(y_75_categorical_24))
y_75_train_categorical_24 = factor24.transform(y_75_categorical_24[0])
y_75_validation_categorical_24 = factor24.transform(y_75_categorical_24[1])
y_75_test_categorical_24 = factor24.transform(y_75_categorical_24[2])

factor48 = LabelEncoder()
factor48.fit(np.concatenate(y_75_categorical_48))
y_75_train_categorical_48 = factor48.transform(y_75_categorical_48[0])
y_75_validation_categorical_48 = factor48.transform(y_75_categorical_48[1])
y_75_test_categorical_48 = factor48.transform(y_75_categorical_48[2])


factor72 = LabelEncoder()
factor72.fit(np.concatenate(y_75_categorical_72))
y_75_train_categorical_72 = factor72.fit_transform(y_75_categorical_72[0])
y_75_validation_categorical_72 = factor72.transform(y_75_categorical_72[1])
y_75_test_categorical_72 = factor72.transform(y_75_categorical_72[2])

"""### Circular Mean Absolute (time) Error"""

def evaluate_circular_mae_cat(model, X, y_true_RAW, label_encoder):
    raw_pred = model.predict(X)
    pred_classes = np.argmax(raw_pred, axis=1)
    y_pred_str = label_encoder.inverse_transform(pred_classes)

    # split string
    y_pred_split = np.array([x.split(':') for x in y_pred_str], dtype=int)

    # make int
    y_pred_time=np.array([[int(i) for i in x] for x in y_pred_split])

    # convert to float using helper func
    y_pred_float = time_to_float(y_pred_time)
    y_true_float = time_to_float(y_true_RAW)

    y_pred_norm = y_pred_float/12
    y_true_norm = y_true_float/12


    # # Circular MAE
    abs_diff = np.abs(y_true_norm - y_pred_norm)
    circular_diff = np.minimum(abs_diff, 1 - abs_diff)
    circular_mae_value = np.mean(circular_diff)
    output= [circular_mae_value,round(circular_mae_value*720,3)]

    return output

"""### Model list and model history initializer"""

history_dict = {}
mae_results =[]

"""### Model Building (30 minutes intervals <-> 24 classes)

First model gives only random guesses, sometimes does find a spot.
"""

# Model building
class_24_model = keras.models.Sequential([
    #Specification of input shape
    keras.layers.Input(shape=(75,75,1)),
    # 3 convolutional layers to sequentially learn edges and what not
    keras.layers.Conv2D(16, (3,3), activation='relu'),
    keras.layers.MaxPooling2D(2,2),
    keras.layers.Conv2D(64, (3,3), activation='relu'),
    keras.layers.MaxPooling2D(2,2),
    keras.layers.Conv2D(128, (3,3), activation='relu'),
    keras.layers.MaxPooling2D(2,2),
    # dropout to bring test accuray on par with train accuracy
    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),
    # One dense layer to  bring condense all information and make global connections
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(24, activation='softmax')
])

class_24_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])

history = class_24_model.fit(x_75_train_cat, y_75_train_categorical_24,
        batch_size=150,
        epochs=20,
        verbose=1,
        validation_data=(x_75_validation_cat, y_75_validation_categorical_24))
score = class_24_model.evaluate(x_75_validation_cat, y_75_validation_categorical_24, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_model, x_75_validation_cat, y_75_validation, factor24))

pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

history_dict['base_24']=history
mae_results.append(["base_24", evaluate_circular_mae_cat(class_24_model, x_75_validation_cat,  y_75_validation, factor24)])

"""#### Addition of batch normalization

Implementation of batch normalization seems to stabilize the model, the model is definitely learning but the validation accuracy is fluctuating.

The best explanation for this phenomena could be grounded into the validation set not being representative of the dataset. Another model is tried with a higher amount of filters in the final layer. This seemed to make it worse. The first model is kept and the learning rate is lowered.
"""

# Model building
class_24_model_BN = keras.models.Sequential([
    #Rescaling to add gray channel to input
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),
    # 3 convolutional layers to get to atleast 0.85 train accuracy

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),
    # One dense layer to  bring condense all information and make global connections
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(24, activation='softmax')
])
class_24_model_BN.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
history= class_24_model_BN.fit(x_75_train_cat, y_75_train_categorical_24,
          batch_size=150,
          epochs=40,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_24))
score = class_24_model_BN.evaluate(x_75_validation_cat, y_75_validation_categorical_24, verbose=0)
history_dict['bn_24']=history
mae_results.append(["bn_24", evaluate_circular_mae_cat(class_24_model_BN, x_75_validation_cat,  y_75_validation, factor24)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_model_BN, x_75_validation_cat, y_75_validation, factor24))

pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""#### Addition of additional dense layer at end"""

# Model building
class_24_model_BN_dense = keras.models.Sequential([
    #Rescaling to add gray channel to input
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),
    # 3 convolutional layers to get to atleast 0.85 train accuracy

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),
    # One dense layer to  bring condense all information and make global connections
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(24, activation='softmax')
])
class_24_model_BN_dense.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
history= class_24_model_BN_dense.fit(x_75_train_cat, y_75_train_categorical_24,
          batch_size=150,
          epochs=20,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_24))
score = class_24_model_BN_dense.evaluate(x_75_validation_cat, y_75_validation_categorical_24, verbose=0)
mae_results.append(["bn_24_dense", evaluate_circular_mae_cat(class_24_model_BN_dense, x_75_validation_cat,  y_75_validation, factor24)])

history_dict['bn_24_dense']=history

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_model_BN_dense, x_75_validation_cat, y_75_validation, factor24))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""#### Addition of another dense layer"""

# Model building
class_24_model_BN_dense_2 = keras.models.Sequential([
    #Rescaling to add gray channel to input
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),
    # 3 convolutional layers to get to atleast 0.85 train accuracy

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),
    # One dense layer to  bring condense all information and make global connections
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(24, activation='softmax')
])


class_24_model_BN_dense_2.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)


history = class_24_model_BN_dense_2.fit(x_75_train_cat, y_75_train_categorical_24,
          batch_size=150,
          epochs=20,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_24))
score = class_24_model_BN_dense_2.evaluate(x_75_validation_cat, y_75_validation_categorical_24, verbose=0)
mae_results.append(["bn_24_dense_2", evaluate_circular_mae_cat(class_24_model_BN_dense_2, x_75_validation_cat,  y_75_validation, factor24)])

history_dict['bn_24_dense_2']=history

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_model_BN_dense_2, x_75_validation_cat, y_75_validation, factor24))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""#### Higher filter count"""

# Model with BatchNormalization and higher filter count in 3th conv layer
class_24_model_BN_filt_inc = keras.models.Sequential([
    #Rescaling to add gray channel to input
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),
    # 3 convolutional layers to get to atleast 0.85 train accuracy

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(256, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),
    # One dense layer to  bring condense all information and make global connections
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(24, activation='softmax')
])
class_24_model_BN_filt_inc.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
history = class_24_model_BN_filt_inc.fit(x_75_train_cat, y_75_train_categorical_24,
          batch_size=150,
          epochs=20,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_24))
score = class_24_model_BN_filt_inc.evaluate(x_75_validation_cat, y_75_validation_categorical_24, verbose=0)
history_dict['bn_24_filt_inc']=history
mae_results.append(["bn_24_filt_inc", evaluate_circular_mae_cat(class_24_model_BN_filt_inc, x_75_validation_cat,  y_75_validation, factor24)])


print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_model_BN_filt_inc, x_75_validation_cat, y_75_validation, factor24))

pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""#### smaller learning rate and more epochs to commomorate"""

# Model with BN and lowered learning rate
class_24_model_BN_lowlearnrate= keras.models.Sequential([
    keras.layers.Input(shape=(75,75,1)),

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),
    # One dense layer to  bring condense all information and make global connections
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(24, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.0005)
class_24_model_BN_lowlearnrate.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history = class_24_model_BN_lowlearnrate.fit(x_75_train_cat, y_75_train_categorical_24,
          batch_size=150,
          epochs=30,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_24))
score = class_24_model_BN_lowlearnrate.evaluate(x_75_validation_cat, y_75_validation_categorical_24, verbose=0)
history_dict['bn_24_lowlearnrate']=history
mae_results.append(["bn_24_lowlearnrate", evaluate_circular_mae_cat(class_24_model_BN_lowlearnrate, x_75_validation_cat,  y_75_validation, factor24)])


print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_model_BN_lowlearnrate, x_75_validation_cat, y_75_validation, factor24))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""#### Switch of BN layer"""

class_24_model_BN_diffpos= keras.models.Sequential([
    keras.layers.Input(shape=(75,75,1)),

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.BatchNormalization(),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),
    # One dense layer to  bring condense all information and make global connections
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(24, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.0005)
class_24_model_BN_diffpos.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history = class_24_model_BN_diffpos.fit(x_75_train_cat, y_75_train_categorical_24,
          batch_size=150,
          epochs=30,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_24))
score = class_24_model_BN_diffpos.evaluate(x_75_validation_cat, y_75_validation_categorical_24, verbose=0)
history_dict['bn_24_diffpos']=history
mae_results.append(["bn_24_diffpos", evaluate_circular_mae_cat(class_24_model_BN_diffpos, x_75_validation_cat,  y_75_validation, factor24)])



print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_model_BN_diffpos, x_75_validation_cat, y_75_validation, factor24))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""### Model 15 minute intervals (48 groups)

Once again without  batch normalization does not work
"""

# Model building
class_48_model = keras.models.Sequential([
    keras.layers.Input(shape=(75,75,1)),
    # 3 convolutional layers to sequentially learn edges and what not
    keras.layers.Conv2D(16, (3,3), activation='relu'),
    keras.layers.MaxPooling2D(2,2),
    keras.layers.Conv2D(64, (3,3), activation='relu'),
    keras.layers.MaxPooling2D(2,2),
    keras.layers.Conv2D(128, (3,3), activation='relu'),
    keras.layers.MaxPooling2D(2,2),
    keras.layers.Conv2D(128, (3,3), activation='relu'),
    keras.layers.MaxPooling2D(2,2),
    # dropout to bring test accuray on par with train accuracy
    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),
    # One dense layer to  bring condense all information and make global connections
    keras.layers.Dense(128, activation='relu'),
    # Second layer to connect important concepts
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(48, activation='softmax')
])
class_48_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
history = class_48_model.fit(x_75_train_cat, y_75_train_categorical_48,
        batch_size=150,
        epochs=20,
        verbose=1,
        validation_data=(x_75_validation_cat, y_75_validation_categorical_48))
score = class_48_model.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_48_model, x_75_validation_cat, y_75_validation, factor48))
history_dict['base_48']=history
mae_results.append(["base_48", evaluate_circular_mae_cat(class_48_model, x_75_validation_cat,  y_75_validation, factor48)])

pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""#### Batch Normalization"""

# Base BN model
class_48_model_BN= keras.models.Sequential([
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(48, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.001)
class_48_model_BN.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history = class_48_model_BN.fit(x_75_train_cat, y_75_train_categorical_48,
          batch_size=150,
          epochs=20,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_48))
score = class_48_model_BN.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['bn_48']=history
mae_results.append(["bn_48", evaluate_circular_mae_cat(class_48_model_BN, x_75_validation_cat,  y_75_validation, factor48)])


print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_48_model_BN, x_75_validation_cat, y_75_validation, factor48))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""#### additional dense layer"""

class_48_model_BN_dense= keras.models.Sequential([
    #Rescaling to add gray channel to input
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),
    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(48, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.001)
class_48_model_BN_dense.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history = class_48_model_BN_dense.fit(x_75_train_cat, y_75_train_categorical_48,
          batch_size=150,
          epochs=20,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_48))
score = class_48_model_BN_dense.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['bn_48_dense']=history
mae_results.append(["bn_48_dense", evaluate_circular_mae_cat(class_48_model_BN_dense, x_75_validation_cat,  y_75_validation, factor48)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_48_model_BN_dense, x_75_validation_cat, y_75_validation, factor48))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""#### Additional conv2d layer with more filters"""

# Model with BN with added conv2d layer
class_48_model_BN2= keras.models.Sequential([
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(256, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(48, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.001)
class_48_model_BN2.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history = class_48_model_BN2.fit(x_75_train_cat, y_75_train_categorical_48,
          batch_size=150,
          epochs=20,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_48))
score = class_48_model_BN2.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['bn_48_dense_conv_add']=history
mae_results.append(["bn_48_dense_conv_add", evaluate_circular_mae_cat(class_48_model_BN2, x_75_validation_cat,  y_75_validation, factor48)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_48_model_BN2, x_75_validation_cat, y_75_validation, factor48))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""#### Model decrease in learning rate"""

# Model with BN with added conv2d layer
class_48_model_BN3= keras.models.Sequential([

    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),
    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),

    keras.layers.Flatten(),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(48, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.0001)
class_48_model_BN3.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history = class_48_model_BN3.fit(x_75_train_cat, y_75_train_categorical_48,
          batch_size=150,
          epochs=40,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_48))
score = class_48_model_BN3.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['bn_48_dense_lowerlearn']=history
mae_results.append(["bn_48_dense_lowerlearn", evaluate_circular_mae_cat(class_48_model_BN3, x_75_validation_cat,  y_75_validation, factor48)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_48_model_BN3, x_75_validation_cat, y_75_validation, factor48))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

# Model with BN with L1 regularization
class_48_model_BN4= keras.models.Sequential([
    #Rescaling to add gray channel to input
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),
    # 3 convolutional layers to get to atleast 0.85 train accuracy

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(256, (3,3),
                        kernel_regularizer=keras.regularizers.l1(0.001)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(48, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.001)
class_48_model_BN4.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history= class_48_model_BN4.fit(x_75_train_cat, y_75_train_categorical_48,
          batch_size=150,
          epochs=20,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_48))
score = class_48_model_BN4.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['bn_48_dense_l1reg']=history
mae_results.append(["bn_48_dense_l1reg", evaluate_circular_mae_cat(class_48_model_BN4, x_75_validation_cat,  y_75_validation, factor48)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_48_model_BN4, x_75_validation_cat, y_75_validation, factor48))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""### 10 minute intervals (72 groups)"""

# Model with BN and lowered learning rate
class_72_model_BN= keras.models.Sequential([
    #Rescaling to add gray channel to input
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),
    # 3 convolutional layers to get to atleast 0.85 train accuracy

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.BatchNormalization(),

    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(72, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.0005)
class_72_model_BN.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history = class_72_model_BN.fit(x_75_train_cat, y_75_train_categorical_72,
          batch_size=150,
          epochs=40,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_72))
score = class_72_model_BN.evaluate(x_75_validation_cat, y_75_validation_categorical_72, verbose=0)
history_dict['bn_72']=history
mae_results.append(["bn_72", evaluate_circular_mae_cat(class_72_model_BN, x_75_validation_cat,  y_75_validation, factor72)])


print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_72_model_BN, x_75_validation_cat, y_75_validation, factor72))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

class_72_L1reg= keras.models.Sequential([
    #Rescaling to add gray channel to input
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),
    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3),
                        kernel_regularizer=keras.regularizers.l1(0.001)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(72, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.0005)
class_72_L1reg.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history= class_72_L1reg.fit(x_75_train_cat, y_75_train_categorical_72,
          batch_size=150,
          epochs=35,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_72))
score = class_72_L1reg.evaluate(x_75_validation_cat, y_75_validation_categorical_72, verbose=0)
history_dict['bn_72_l1reg']=history
mae_results.append(["bn_72_l1reg", evaluate_circular_mae_cat(class_72_L1reg, x_75_validation_cat, y_75_validation, factor72)])


print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_72_L1reg, x_75_validation_cat, y_75_validation, factor72))
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

# Model with BN and lowered learning rate
class_72_L1reg_2= keras.models.Sequential([
    #Rescaling to add gray channel to input
    keras.layers.Rescaling(1./1, input_shape=(75, 75, 1)),
    # 3 convolutional layers to get to atleast 0.85 train accuracy

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3),
                        kernel_regularizer=keras.regularizers.l1(0.001)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3),
                        kernel_regularizer=keras.regularizers.l1(0.001)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),
    # One dense layer to  bring condense all information and make global connections
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(72, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.0005)
class_72_L1reg_2.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history_L1_72_2 = class_72_L1reg_2.fit(x_75_train_cat, y_75_train_categorical_72,
          batch_size=150,
          epochs=40,
          verbose=1,
          validation_data=(x_75_validation_cat, y_75_validation_categorical_72))
score = class_72_L1reg_2.evaluate(x_75_validation_cat, y_75_validation_categorical_72, verbose=0)
history_dict['bn_72_l1reg_2']=history
mae_results.append(["bn_72_l1reg_2", evaluate_circular_mae_cat(class_72_L1reg_2, x_75_validation_cat, y_75_validation, factor72)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_72_L1reg_2, x_75_validation_cat, y_75_validation, factor72))
pd.DataFrame(history_L1_72_2.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""### Transfer Learning chain

#### Base model, keep all layers of previous model trainable
"""

for i, layer in enumerate(class_24_model_BN_lowlearnrate.layers):
    print(i, layer.name, layer.output_shape if hasattr(layer, "output_shape") else "no output")

# Call the model once to define input/output
_ = class_24_model_BN_lowlearnrate(tf.zeros((1, 75, 75, 1)))

feature_extractor = keras.Sequential(class_24_model_BN_lowlearnrate.layers[:-1])


# Build functional model
inputs = keras.Input(shape=(75, 75, 1))
features = feature_extractor(inputs)

# Add new dense layers for 48-class classification
x = keras.layers.Dense(256, activation='relu')(features)
x = keras.layers.Dropout(0.5)(x)
x = keras.layers.Dense(256, activation='relu')(x)
outputs_48 = keras.layers.Dense(48, activation='softmax')(x)

class_24_to_48_model = keras.Model(inputs=inputs, outputs=outputs_48)

# Compile
class_24_to_48_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history_24_48 = class_24_to_48_model.fit(
    x_75_train_cat, y_75_train_categorical_48,
    batch_size=150,
    epochs=20,
    verbose=1,
    validation_data=(x_75_validation_cat, y_75_validation_categorical_48)
)

# Evaluate
score = class_24_to_48_model.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['24_to_48'] = history_24_48
mae_results.append(["24_to_48", evaluate_circular_mae_cat(class_24_to_48_model, x_75_validation_cat, y_75_validation, factor48)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_to_48_model, x_75_validation_cat, y_75_validation, factor48))

# Plot training curves
pd.DataFrame(history_24_48.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
plt.show()

"""#### Freeze first 2 convolutional blocks"""

# Call the model once to define input/output
_ = class_24_model_BN_lowlearnrate(tf.zeros((1, 75, 75, 1)))

feature_extractor = keras.Sequential(class_24_model_BN_lowlearnrate.layers[:-1])


# Freeze early layers
for layer in feature_extractor.layers[:5]:
    layer.trainable = False

# Build functional model
inputs = keras.Input(shape=(75, 75, 1))
features = feature_extractor(inputs)

# Add new dense layers for 48-class classification
x = keras.layers.Dense(256, activation='relu')(features)
x = keras.layers.Dropout(0.5)(x)
x = keras.layers.Dense(256, activation='relu')(x)
outputs_48 = keras.layers.Dense(48, activation='softmax')(x)

class_24_to_48_model_freeze = keras.Model(inputs=inputs, outputs=outputs_48)

# Compile
class_24_to_48_model_freeze.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history_24_48 = class_24_to_48_model_freeze.fit(
    x_75_train_cat, y_75_train_categorical_48,
    batch_size=150,
    epochs=20,
    verbose=1,
    validation_data=(x_75_validation_cat, y_75_validation_categorical_48)
)

# Evaluate
score = class_24_to_48_model_freeze.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['24_to_48_freeze'] = history_24_48
mae_results.append(["24_to_48_freeze", evaluate_circular_mae_cat(class_24_to_48_model_freeze, x_75_validation_cat, y_75_validation, factor48)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_to_48_model_freeze, x_75_validation_cat, y_75_validation, factor48))

# Plot training curves
pd.DataFrame(history_24_48.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
plt.show()

"""#### Freeze all convolutional blocks"""

# Call the model once to define input/output
_ = class_24_model_BN_lowlearnrate(tf.zeros((1, 75, 75, 1)))

feature_extractor = keras.Sequential(class_24_model_BN_lowlearnrate.layers[:-1])


# Freeze early layers
for layer in feature_extractor.layers[:9]:
    layer.trainable = False

# Build functional model
inputs = keras.Input(shape=(75, 75, 1))
features = feature_extractor(inputs)

# Add new dense layers for 48-class classification
x = keras.layers.Dense(256, activation='relu')(features)
x = keras.layers.Dropout(0.5)(x)
x = keras.layers.Dense(256, activation='relu')(x)
outputs_48 = keras.layers.Dense(48, activation='softmax')(x)

class_24_to_48_model_freeze2 = keras.Model(inputs=inputs, outputs=outputs_48)

# Compile
class_24_to_48_model_freeze2.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history_24_48 = class_24_to_48_model_freeze2.fit(
    x_75_train_cat, y_75_train_categorical_48,
    batch_size=150,
    epochs=20,
    verbose=1,
    validation_data=(x_75_validation_cat, y_75_validation_categorical_48)
)

# Evaluate
score = class_24_to_48_model_freeze2.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['24_to_48_freeze2'] = history_24_48
mae_results.append(["24_to_48_freeze2", evaluate_circular_mae_cat(class_24_to_48_model_freeze2, x_75_validation_cat, y_75_validation, factor48)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_to_48_model_freeze2, x_75_validation_cat, y_75_validation, factor48))

# Plot training curves
pd.DataFrame(history_24_48.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
plt.show()

"""#### Freeze no layers, remove dropout"""

# Call the model once to define input/output
_ = class_24_model_BN_lowlearnrate(tf.zeros((1, 75, 75, 1)))

feature_extractor = keras.Sequential(class_24_model_BN_lowlearnrate.layers[:-1])


# Build functional model
inputs = keras.Input(shape=(75, 75, 1))
features = feature_extractor(inputs)

# Add new dense layers for 48-class classification
x = keras.layers.Dense(256, activation='relu')(features)
x = keras.layers.Dense(256, activation='relu')(x)
outputs_48 = keras.layers.Dense(48, activation='softmax')(x)

class_24_to_48_model = keras.Model(inputs=inputs, outputs=outputs_48)

# Compile
class_24_to_48_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history_24_48 = class_24_to_48_model.fit(
    x_75_train_cat, y_75_train_categorical_48,
    batch_size=150,
    epochs=20,
    verbose=1,
    validation_data=(x_75_validation_cat, y_75_validation_categorical_48)
)

# Evaluate
score = class_24_to_48_model.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['24_to_48_nodrouput'] = history_24_48
mae_results.append(["24_to_48_nodrouput", evaluate_circular_mae_cat(class_24_to_48_model, x_75_validation_cat, y_75_validation, factor48)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_to_48_model, x_75_validation_cat, y_75_validation, factor48))

# Plot training curves
pd.DataFrame(history_24_48.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
plt.show()

"""#### Increased dense layers"""

# Call the model once to define input/output
_ = class_24_model_BN_lowlearnrate(tf.zeros((1, 75, 75, 1)))

feature_extractor = keras.Sequential(class_24_model_BN_lowlearnrate.layers[:-1])


# Build functional model
inputs = keras.Input(shape=(75, 75, 1))
features = feature_extractor(inputs)

# Add new dense layers for 48-class classification
x = keras.layers.Dense(256, activation='relu')(features)
x = keras.layers.Dense(256, activation='relu')(x)
x = keras.layers.Dense(256, activation='relu')(x)

outputs_48 = keras.layers.Dense(48, activation='softmax')(x)

class_24_to_48_model_best = keras.Model(inputs=inputs, outputs=outputs_48)

# Compile
class_24_to_48_model_best.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history_24_48 = class_24_to_48_model_best.fit(
    x_75_train_cat, y_75_train_categorical_48,
    batch_size=150,
    epochs=20,
    verbose=1,
    validation_data=(x_75_validation_cat, y_75_validation_categorical_48)
)

# Evaluate
score = class_24_to_48_model_best.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['24_to_48_moredense'] = history_24_48
mae_results.append(["24_to_48_moredense", evaluate_circular_mae_cat(class_24_to_48_model_best, x_75_validation_cat, y_75_validation, factor48)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_to_48_model_best, x_75_validation_cat, y_75_validation, factor48))

# Plot training curves
pd.DataFrame(history_24_48.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
plt.show()

"""#### Lowered demse on last layer"""

# Call the model once to define input/output
_ = class_24_model_BN_lowlearnrate(tf.zeros((1, 75, 75, 1)))

feature_extractor = keras.Sequential(class_24_model_BN_lowlearnrate.layers[:-1])


# Build functional model
inputs = keras.Input(shape=(75, 75, 1))
features = feature_extractor(inputs)

# Add new dense layers for 48-class classification
x = keras.layers.Dense(256, activation='relu')(features)
x = keras.layers.Dense(256, activation='relu')(x)
x = keras.layers.Dense(128, activation='relu')(x)

outputs_48 = keras.layers.Dense(48, activation='softmax')(x)

class_24_to_48_model = keras.Model(inputs=inputs, outputs=outputs_48)

# Compile
class_24_to_48_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history_24_48 = class_24_to_48_model.fit(
    x_75_train_cat, y_75_train_categorical_48,
    batch_size=150,
    epochs=20,
    verbose=1,
    validation_data=(x_75_validation_cat, y_75_validation_categorical_48)
)

# Evaluate
score = class_24_to_48_model.evaluate(x_75_validation_cat, y_75_validation_categorical_48, verbose=0)
history_dict['24_to_48_moredense_2'] = history_24_48
mae_results.append(["24_to_48_moredense_2", evaluate_circular_mae_cat(class_24_to_48_model, x_75_validation_cat, y_75_validation, factor48)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_to_48_model, x_75_validation_cat, y_75_validation, factor48))

# Plot training curves
pd.DataFrame(history_24_48.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
plt.show()

"""#### 48_to_72 model"""

# Call once to ensure inputs are defined
_ = class_24_to_48_model_best(tf.zeros((1, 75, 75, 1)))

feature_extractor = keras.Sequential(class_24_model_BN_lowlearnrate.layers[:-1])

# Build functional model
inputs = keras.Input(shape=(75, 75, 1))
features = feature_extractor(inputs)

x = keras.layers.Dense(256, activation='relu')(features)
x = keras.layers.Dense(256, activation='relu')(x)
x = keras.layers.Dense(256, activation='relu')(x)
outputs_72 = keras.layers.Dense(72, activation='softmax')(x)

class_48_to_72_model = keras.Model(inputs=inputs, outputs=outputs_72)

class_48_to_72_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_48_72 = class_48_to_72_model.fit(
    x_75_train_cat, y_75_train_categorical_72,
    batch_size=150,
    epochs=30,
    verbose=1,
    validation_data=(x_75_validation_cat, y_75_validation_categorical_72)
)


score = class_48_to_72_model.evaluate(
    x_75_validation_cat, y_75_validation_categorical_72, verbose=0)
history_dict['48_to_72']=history_24_48
mae_results.append(["48_to_72", evaluate_circular_mae_cat(class_48_to_72_model, x_75_validation_cat, y_75_validation, factor72)])

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_48_to_72_model, x_75_validation_cat, y_75_validation, factor72))
pd.DataFrame(history_48_72.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

"""### Summary table"""

###THIS CAN BE SAFELY DELTED, PURELY HERE FOR DEBUGGING PURPOSES
# mae_results.append(["48_to_72", evaluate_circular_mae_cat(class_48_to_72_model, x_75_validation_cat, y_75_validation, factor72)])
# mae_results.append(["24_to_48", evaluate_circular_mae_cat(class_24_to_48_model, x_75_validation_cat, y_75_validation, factor48)])
# mae_results.append(["bn_72_l1reg_2", evaluate_circular_mae_cat(class_72_L1reg_2, x_75_validation_cat, y_75_validation, factor72)])
# mae_results.append(["bn_72_l1reg", evaluate_circular_mae_cat(class_72_L1reg, x_75_validation_cat, y_75_validation, factor72)])
# mae_results.append(["bn_72", evaluate_circular_mae_cat(class_72_model_BN, x_75_validation_cat,  y_75_validation, factor72)])
# mae_results.append(["bn_48_dense_l1reg", evaluate_circular_mae_cat(class_48_model_BN4, x_75_validation_cat,  y_75_validation, factor48)])
# mae_results.append(["bn_48_dense_lowerlearn", evaluate_circular_mae_cat(class_48_model_BN3, x_75_validation_cat,  y_75_validation, factor48)])
# mae_results.append(["bn_48_dense_conv_add", evaluate_circular_mae_cat(class_48_model_BN2, x_75_validation_cat,  y_75_validation, factor48)])
# mae_results.append(["bn_48_dense", evaluate_circular_mae_cat(class_48_model_BN_dense, x_75_validation_cat,  y_75_validation, factor48)])
# mae_results.append(["bn_48", evaluate_circular_mae_cat(class_48_model_BN, x_75_validation_cat,  y_75_validation, factor48)])
# mae_results.append(["base_48", evaluate_circular_mae_cat(class_48_model, x_75_validation_cat,  y_75_validation, factor48)])
# mae_results.append(["bn_24_diffpos", evaluate_circular_mae_cat(class_24_model_BN_diffpos, x_75_validation_cat,  y_75_validation, factor24)])
# mae_results.append(["bn_24_lowlearnrate", evaluate_circular_mae_cat(class_24_model_BN_lowlearnrate, x_75_validation_cat,  y_75_validation, factor24)])
# mae_results.append(["bn_24_filt_inc", evaluate_circular_mae_cat(class_24_model_BN_filt_inc, x_75_validation_cat,  y_75_validation, factor24)])
# mae_results.append(["bn_24_dense_2", evaluate_circular_mae_cat(class_24_model_BN_dense_2, x_75_validation_cat,  y_75_validation, factor24)])
# mae_results.append(["bn_24_dense", evaluate_circular_mae_cat(class_24_model_BN_dense, x_75_validation_cat,  y_75_validation, factor24)])
# mae_results.append(["bn_24", evaluate_circular_mae_cat(class_24_model_BN, x_75_validation_cat,  y_75_validation, factor24)])
# mae_results.append(["base_24", evaluate_circular_mae_cat(class_24_model, x_75_validation_cat,  y_75_validation, factor24)])

summary = []

for name, hist in history_dict.items():
    metrics = hist.history.keys()

    # Safely get last values for loss/accuracy and val_loss/val_accuracy
    final_metrics = {m: hist.history[m][-1] for m in metrics if len(hist.history[m]) > 0}

    # Add model name
    final_metrics['model'] = name
    summary.append(final_metrics)

# Create DataFrame
df_summary = pd.DataFrame(summary)

# Reorder columns nicely
cols_order = ['model'] + [c for c in df_summary.columns if c != 'model']
df_summary = df_summary[cols_order]

# Sort or format
df_summary = df_summary.round(4)

# Convert each MAE to a scalar float
mae_results = [[name, float(np.ravel(mae)[0])] for name, mae in mae_results]

df_mae = pd.DataFrame(mae_results, columns=["model", "mae"])
df_mae["mae_minutes"] = (df_mae["mae"] * 720).round(3)
df_full = pd.merge(df_summary, df_mae, on="model", how="left")

df_full

df_full.sort_values('mae')

"""### Testing best models on test set"""

print('model trained on 24 categories with batch normalization')
print(class_24_model_BN_lowlearnrate.evaluate(x_75_test_cat, y_75_test_categorical_24))
print(evaluate_circular_mae_cat(class_24_model_BN_lowlearnrate, x_75_test_cat, y_75_test, factor24))
print('\n')

print('model trained on 72 categories with batch normalization')
print(class_72_model_BN.evaluate(x_75_test_cat, y_75_test_categorical_48))
print(evaluate_circular_mae_cat(class_48_model_BN, x_75_test_cat, y_75_test, factor48))
print('\n')

print('Transfer learning 24 to 48')
print(class_24_to_48_model.evaluate(x_75_test_cat, y_75_test_categorical_48))
print(evaluate_circular_mae_cat(class_24_to_48_model, x_75_test_cat, y_75_test, factor48))
print('\n')

print('Transfer learning 48 to 72')
print(class_48_to_72_model.evaluate(x_75_test_cat, y_75_test_categorical_72))
print(evaluate_circular_mae_cat(class_48_to_72_model, x_75_test_cat, y_75_test, factor72))

"""### Train, validate and test best models on larger"""

# Load big dataset to start training
x_150 = np.load("A1_data_150/images.npy")
y_150 = np.load("A1_data_150/labels.npy")

# Normalise inputs, as in task 1
x_150 = x_150.astype('float32') / 255.0

# Split into training and test set and shuffle and since the datasets are ordered, it is recommended in the assignment spec to shuffle
x_150_train, x_150_test, y_150_train, y_150_test = train_test_split(x_150, y_150, test_size = 0.10, random_state = 2029197, shuffle = True)

# Split again into training-validation sets
x_150_train, x_150_validation, y_150_train, y_150_validation = train_test_split(x_150_train, y_150_train, test_size = 0.10, random_state = 202197)


# Given grayscale images it has to be added to the information i.e. shape from (n,75,75) to (n,75,75,1)
x_150_train_cat = np.expand_dims(x_150_train, axis=-1)
x_150_validation_cat = np.expand_dims(x_150_validation, axis=-1)
x_150_test_cat = np.expand_dims(x_150_test, axis=-1)

arrays = [y_150_train, y_150_validation, y_150_test]

# Make categorical tests for 30 (24 classes), 15 (48 classes) and 10 (72 classes) minutes intervals
y_150_categorical_24 = [split_into_bins(arr,30) for arr in arrays]
y_150_categorical_48 = [split_into_bins(arr,15) for arr in arrays]
y_150_categorical_72 = [split_into_bins(arr,10) for arr in arrays]

# Turn the string-based categories into factors in order to let our model know that this is a categorical variable
factor24 = LabelEncoder()
factor24.fit(np.concatenate(y_150_categorical_24))
y_150_train_categorical_24 = factor24.transform(y_150_categorical_24[0])
y_150_validation_categorical_24 = factor24.transform(y_150_categorical_24[1])
y_150_test_categorical_24 = factor24.transform(y_150_categorical_24[2])

factor48 = LabelEncoder()
factor48.fit(np.concatenate(y_150_categorical_48))
y_150_train_categorical_48 = factor48.transform(y_150_categorical_48[0])
y_150_validation_categorical_48 = factor48.transform(y_150_categorical_48[1])
y_150_test_categorical_48 = factor48.transform(y_150_categorical_48[2])


factor72 = LabelEncoder()
factor72.fit(np.concatenate(y_150_categorical_72))
y_150_train_categorical_72 = factor72.fit_transform(y_150_categorical_72[0])
y_150_validation_categorical_72 = factor72.transform(y_150_categorical_72[1])
y_150_test_categorical_72 = factor72.transform(y_150_categorical_72[2])

class_24_model_BN_lowlearnrate= keras.models.Sequential([
    keras.layers.Input(shape=(150,150,1)),

    keras.layers.Conv2D(16, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3)),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3)),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Dropout(0.5),
    keras.layers.Flatten(),
    # One dense layer to  bring condense all information and make global connections
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(24, activation='softmax')
])

opt = keras.optimizers.Adam(learning_rate=0.0005)
class_24_model_BN_lowlearnrate.compile(
    optimizer=opt,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
    )

history = class_24_model_BN_lowlearnrate.fit(x_150_train_cat, y_150_train_categorical_24,
          batch_size=150,
          epochs=30,
          verbose=1,
          validation_data=(x_150_validation_cat, y_150_validation_categorical_24))
score = class_24_model_BN_lowlearnrate.evaluate(x_150_validation_cat, y_150_validation_categorical_24, verbose=0)

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_model_BN_lowlearnrate, x_150_validation_cat, y_150_validation, factor24))

pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()

# Call the model once to define input/output
_ = class_24_model_BN_lowlearnrate(tf.zeros((1, 150, 150, 1)))

feature_extractor = keras.Sequential(class_24_model_BN_lowlearnrate.layers[:-1])


# Build functional model
inputs = keras.Input(shape=(150, 150, 1))
features = feature_extractor(inputs)

# Add new dense layers for 48-class classification
x = keras.layers.Dense(256, activation='relu')(features)
x = keras.layers.Dense(256, activation='relu')(x)
x = keras.layers.Dense(256, activation='relu')(x)

outputs_48 = keras.layers.Dense(48, activation='softmax')(x)

class_24_to_48_model_best = keras.Model(inputs=inputs, outputs=outputs_48)

# Compile
class_24_to_48_model_best.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history_24_48 = class_24_to_48_model_best.fit(
    x_150_train_cat, y_150_train_categorical_48,
    batch_size=150,
    epochs=20,
    verbose=1,
    validation_data=(x_150_validation_cat, y_150_validation_categorical_48)
)

# Evaluate
score = class_24_to_48_model_best.evaluate(x_150_validation_cat, y_150_validation_categorical_48, verbose=0)

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_24_to_48_model_best, x_150_validation_cat, y_150_validation, factor48))

# Plot training curves
pd.DataFrame(history_24_48.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
plt.show()

# Call once to ensure inputs are defined
_ = class_24_to_48_model_best(tf.zeros((1, 150, 150, 1)))

feature_extractor = keras.Sequential(class_24_to_48_model_best.layers[:-1])

# Build functional model
inputs = keras.Input(shape=(150, 150, 1))
features = feature_extractor(inputs)

x = keras.layers.Dense(256, activation='relu')(features)
x = keras.layers.Dense(256, activation='relu')(x)
x = keras.layers.Dense(256, activation='relu')(x)
outputs_72 = keras.layers.Dense(72, activation='softmax')(x)

class_48_to_72_model = keras.Model(inputs=inputs, outputs=outputs_72)

class_48_to_72_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_48_72 = class_48_to_72_model.fit(
    x_150_train_cat, y_150_train_categorical_72,
    batch_size=150,
    epochs=30,
    verbose=1,
    validation_data=(x_150_validation_cat, y_150_validation_categorical_72)
)


score = class_48_to_72_model.evaluate(
    x_150_validation_cat, y_150_validation_categorical_72, verbose=0)

print('Test loss:', score[0])
print('Test accuracy:', score[1])
print(evaluate_circular_mae_cat(class_48_to_72_model, x_150_validation_cat, y_150_validation, factor72))

pd.DataFrame(history_48_72.history).plot(figsize=(8, 5))
plt.grid(True)
plt.xlabel("Epochs")
plt.ylabel("Loss/Accuracy")
#plt.gca().set_ylim(0, 1)
plt.show()